repos:
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.259
      hooks:
          - id: ruff
            args: ['--fix']

    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-merge-conflict
          - id: debug-statements
          - id: check-docstring-first
          - id: check-json
            exclude: tsconfig.json
          - id: end-of-file-fixer
            exclude: \.min\.
          - id: fix-byte-order-marker
          - id: forbid-new-submodules
          - id: mixed-line-ending
            args: ['--fix=lf']
          - id: trailing-whitespace
